### ISSUE TITLE
M1 build results (not a real bug)

### ISSUE THREAD

**Issue by elektrobohemian** [KALMUS-Color-Toolkit/KALMUS#4]
* KALMUS will not build natively on M1 
* as expected this is related to the dependecy on numpy and scikit-*
* there is a possible workaround using miniconda that I haven't tested
* you might want to let your users know about this issue although most Apple users should be aware of the problem (they can still use a Rosetta-managed terminal)

**Comment by yc015** [comment]
Thank you so much for your feedback! I will write a warning in the installation guide for the Apple M1 users.

**Comment by yc015** [comment]
Hello @elektrobohemian! I have added a [section](https://github.com/KALMUS-Color-Toolkit/KALMUS#for-users-with-apple-m1-chip-arm64-architecture) about this issue in the installation guide. 

Following your hints, I iterated through several posts about the Miniconda. I proposed a [tentative fix](https://github.com/KALMUS-Color-Toolkit/KALMUS#for-users-with-apple-m1-chip-arm64-architecture) following the recommendations I saw. However, I don't have a machine with arm64 architecture available to me right now so I didn't validate this fix. Will you be interested in testing this fix on your M1 machine?

Thank you again for this build result on your M1 machine!

**Comment by elektrobohemian** [comment]
cool, thank you. I didn't expect that you would write so much about the issue. I had expected that you would just write that M1 users should stick with Rosetta emulation. I will test it anyhow. I guess the information is more than helpful for users that are not much into developing software.

**Comment by elektrobohemian** [comment]
* the solution will not work as conda supports only Python 3.9 on M1 architectures, haven't tested mambaforge though

I would suggest to remove the information and state that the software will not build natively under M1 (at the time of writing) because of its dependency on NumPy. most M1 users should be expecting this issue. to facilitate the installation, I would recommend that M1 users should use a Python 3.7 enviroment under Rosetta emulation. this will save you from support calls...

**Comment by elektrobohemian** [comment]
by the way, KALMUS will build fine with Rosetta emulation under M1
```
 ~/src/python/kalmus  pip show kalmus                                                                   
Name: kalmus
Version: 1.3.8
Summary: kalmus film color analysis tool
Home-page: https://github.com/KALMUS-Color-Toolkit/KALMUS
Author: Yida Chen, Eric Faden, Nathan Ryan
Author-email: yc015@bucknell.edu
License: MIT
Location: /Users/david/src/python/kalmus/venv/lib/python3.8/site-packages
Requires: scikit-image, scikit-learn, opencv-python, numpy, scipy, matplotlib, kiwisolver, biopython
```

**Comment by yc015** [comment]
Thank you so much for the results! I just rewrote the [warning](https://github.com/KALMUS-Color-Toolkit/KALMUS#for-users-with-apple-m1-chip-arm64-architecture) to clearly state this fact.
